apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service: monitoring
resources:
  - thanos-query-frontend.yaml
images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.25.0
