apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service: monitoring
resources:
  - n9e-webapi.yaml
images:
  - name: n9e
    newName: ulric2019/nightingale
    newTag: 5.6.2